#!/usr/bin/env bash

# inputs
INPUT_SCRIPT=$1
INPUT_ARGVS=${@:2}

echo "+ INPUT_ARGVS: $INPUT_ARGVS"

# if the input script is not found, exit
if [ ! -f $INPUT_SCRIPT ]; then
    echo "$INPUT_SCRIPT not found"
    exit 1
fi

# modules
nvidia-smi

# envs
export CUDA_LAUNCH_BLOCKING=1
export OMP_NUM_THREADS=1

export VLLM_ENABLE_V1_MULTIPROCESSING=0
export VLLM_USE_FLASHINFER_SAMPLER=0

# debug
# export NCCL_DEBUG=INFO
# export TORCH_CPP_LOG_LEVEL=INFO
# export TORCH_DISTRIBUTED_DEBUG=DETAIL
# export VLLM_LOGGING_LEVEL=DEBUG

# nums of GPUs
NGPUS=$(nvidia-smi -L | wc -l)
echo "+ NGPUS: $NGPUS"
if [ $NGPUS -eq 0 ]; then
    echo "No GPU found"
    exit 1
fi

# Find an available port and use it
PORT=$(python3 -c 'import socket; s = socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close();')

# fire up
set -x
torchrun \
    --rdzv_id $RANDOM \
    --rdzv_backend c10d \
    --rdzv-endpoint localhost:$PORT \
    --nnode 1 \
    --nproc_per_node $NGPUS \
    $INPUT_SCRIPT \
    $INPUT_ARGVS